# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Azure_Vmware_Solution(_Azure):
    _type = "Azure_VMware_Solution"
    _icon_dir = "resources/azure/Azure_VMware_Solution"


class Avs(_Azure_Vmware_Solution):
    _icon = "avs.png"


# Aliases
