# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Internet_Of_Things(_Azure):
    _type = "Internet_of_Things"
    _icon_dir = "resources/azure/Internet_of_Things"


class DigitalTwins(_Internet_Of_Things):
    _icon = "digital-twins.png"


class TimeSeriesInsightsAccessPolicies(_Internet_Of_Things):
    _icon = "time-series-insights-access-policies.png"


# Aliases
