# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Mixed_Reality(_Azure):
    _type = "Mixed_Reality"
    _icon_dir = "resources/azure/Mixed_Reality"


class RemoteRendering(_Mixed_Reality):
    _icon = "remote-rendering.png"


# Aliases
