# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Azure


class _Web(_Azure):
    _type = "Web"
    _icon_dir = "resources/azure/Web"


class MediaService(_Web):
    _icon = "media-service.png"


class NotificationHubNamespaces(_Web):
    _icon = "notification-hub-namespaces.png"


# Aliases
